### ISSUE TITLE
uk.oczadly.karl.jnano.rpc.exception.RpcEntityNotFoundException: Wallet not found

### ISSUE THREAD

**Issue by letskingit** [koczadly/jNano#3]
Hey again,
I am getting the error shown in the title within this code block(on the processRequest line) code:
String seed = 978B57EDDE3DA88D97930A1B58082920A2A496B5BF3F6085F4EFF3AB0411942C;
RequestAccountCreate request = new RequestAccountCreate(seed);
ResponseAccount response = node.processRequest(request); //error caught here
accountAddress = response.getAccountAddress();

What do I need to do?
Heres some free nano for your help - (awesome tipping service for nano) https://heytip.me/?claim=puqwv4935

Cheers

**Comment by koczadly** [comment]
Hey bro, I appreciate you using my library and sending a tip, thank you 😊

The problem here is that `RequestAccountCreate` (account_create) takes a wallet ID as the argument, and not a seed. To create an account from a seed, you're probably wanting to use the deterministic_key command, represented by the `RequestDeterministicKey` class. You'll need to provide an index along with the seed — if you don't know what that value is or should be, just use the number zero.

**Comment by letskingit** [comment]
Hey thanks for the quick response!
Will try that class instead. 

Will close the issue once I test it.

**Comment by letskingit** [comment]
Also whats the best way to generate a random walletID?

**Comment by letskingit** [comment]
So just used the wallet_create rpc call using curl, from there I will create accounts with that wallet ID.
Creating a new seed for every account was my initial thought.
Then I thought each new account required its own wallet ID.
Finally figured out new accounts don't need there own wallet ID.

Just saw RequestWalletCreate, that is what I could use.
New to nano development, not sure how everything works.

Sorry for the confusion.

**Comment by koczadly** [comment]
No worries, glad you got it all figured out. If you ever need further assistance and have discord, you can add me at Karl#8079
